create extension if not exists pgcrypto;

do $$
begin
  create type public.admin_role as enum ('owner', 'editor');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.admin_role not null default 'editor',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cms_status (
  id text primary key,
  initialized boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key,
  content jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.homepage_content (
  id text primary key,
  content jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.excursions (
  slug text primary key check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  visible boolean not null default true,
  sort_order integer not null default 0,
  content jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.gallery_images (
  id text primary key,
  src text not null,
  alt text not null default '',
  storage_path text,
  sort_order integer not null default 0,
  visible boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.faqs (
  id text primary key,
  question text not null,
  answer text not null,
  sort_order integer not null default 0,
  visible boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.content_revisions (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  old_data jsonb,
  new_data jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
      and active = true
  );
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
      and active = true
      and role = 'owner'
  );
$$;

revoke all on function public.is_admin() from public;
revoke all on function public.is_owner() from public;
grant execute on function public.is_admin() to anon, authenticated;
grant execute on function public.is_owner() to authenticated;

create or replace function public.set_cms_audit_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  return new;
end;
$$;

create or replace function public.record_content_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_row jsonb;
  next_row jsonb;
  row_id text;
begin
  previous_row := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  next_row := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  row_id := coalesce(next_row ->> 'id', next_row ->> 'slug', previous_row ->> 'id', previous_row ->> 'slug', 'unknown');
  insert into public.content_revisions(table_name, record_id, old_data, new_data, changed_by)
  values (tg_table_name, row_id, previous_row, next_row, auth.uid());
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function public.set_cms_audit_fields() from public;
revoke all on function public.record_content_revision() from public;

do $$
declare
  table_name text;
begin
  foreach table_name in array array['site_settings', 'homepage_content', 'excursions', 'gallery_images', 'faqs']
  loop
    execute format('drop trigger if exists set_cms_audit_fields on public.%I', table_name);
    execute format('create trigger set_cms_audit_fields before insert or update on public.%I for each row execute function public.set_cms_audit_fields()', table_name);
    execute format('drop trigger if exists record_content_revision on public.%I', table_name);
    execute format('create trigger record_content_revision after insert or update or delete on public.%I for each row execute function public.record_content_revision()', table_name);
  end loop;
end $$;

alter table public.admin_users enable row level security;
alter table public.cms_status enable row level security;
alter table public.site_settings enable row level security;
alter table public.homepage_content enable row level security;
alter table public.excursions enable row level security;
alter table public.gallery_images enable row level security;
alter table public.faqs enable row level security;
alter table public.content_revisions enable row level security;

grant select on public.cms_status, public.site_settings, public.homepage_content, public.excursions, public.gallery_images, public.faqs to anon;
grant select, insert, update, delete on public.cms_status, public.site_settings, public.homepage_content, public.excursions, public.gallery_images, public.faqs to authenticated;
grant select on public.admin_users, public.content_revisions to authenticated;

drop policy if exists "Admin can read own access" on public.admin_users;
create policy "Admin can read own access" on public.admin_users
  for select to authenticated using (user_id = (select auth.uid()));
drop policy if exists "Owners manage administrators" on public.admin_users;
create policy "Owners manage administrators" on public.admin_users
  for all to authenticated using (public.is_owner()) with check (public.is_owner());

drop policy if exists "Public can read CMS status" on public.cms_status;
create policy "Public can read CMS status" on public.cms_status for select to anon, authenticated using (true);
drop policy if exists "Admins manage CMS status" on public.cms_status;
create policy "Admins manage CMS status" on public.cms_status for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings" on public.site_settings for select to anon, authenticated using (true);
drop policy if exists "Admins manage site settings" on public.site_settings;
create policy "Admins manage site settings" on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read homepage" on public.homepage_content;
create policy "Public can read homepage" on public.homepage_content for select to anon, authenticated using (true);
drop policy if exists "Admins manage homepage" on public.homepage_content;
create policy "Admins manage homepage" on public.homepage_content for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read visible excursions" on public.excursions;
create policy "Public can read visible excursions" on public.excursions for select to anon, authenticated using (visible = true or public.is_admin());
drop policy if exists "Admins manage excursions" on public.excursions;
create policy "Admins manage excursions" on public.excursions for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read visible gallery" on public.gallery_images;
create policy "Public can read visible gallery" on public.gallery_images for select to anon, authenticated using (visible = true or public.is_admin());
drop policy if exists "Admins manage gallery" on public.gallery_images;
create policy "Admins manage gallery" on public.gallery_images for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public can read visible FAQs" on public.faqs;
create policy "Public can read visible FAQs" on public.faqs for select to anon, authenticated using (visible = true or public.is_admin());
drop policy if exists "Admins manage FAQs" on public.faqs;
create policy "Admins manage FAQs" on public.faqs for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins read revisions" on public.content_revisions;
create policy "Admins read revisions" on public.content_revisions for select to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-media', 'site-media', true, 8388608, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins can list site media" on storage.objects;
create policy "Admins can list site media" on storage.objects for select to authenticated
  using (bucket_id = 'site-media' and public.is_admin());
drop policy if exists "Admins can upload site media" on storage.objects;
create policy "Admins can upload site media" on storage.objects for insert to authenticated
  with check (bucket_id = 'site-media' and public.is_admin());
drop policy if exists "Admins can update site media" on storage.objects;
create policy "Admins can update site media" on storage.objects for update to authenticated
  using (bucket_id = 'site-media' and public.is_admin())
  with check (bucket_id = 'site-media' and public.is_admin());
drop policy if exists "Admins can delete site media" on storage.objects;
create policy "Admins can delete site media" on storage.objects for delete to authenticated
  using (bucket_id = 'site-media' and public.is_admin());
