name: Verificar sitio web

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Preparar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.13.0"
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Revisar código
        run: npm run lint

      - name: Compilar y probar
        run: npm test
